-- Auto-generated by simple-linux monitor resolver
-- Edit config.env (SL_MONITOR_ORDER) and run: sl-controller.sh update-monitors
hl.monitor({
  output = "HDMI-A-1",
  mode = "2560x1440@144.00000",
  position = "0x0",
  scale = "0.67",
})

hl.monitor({
  output = "DP-1",
  mode = "3840x2160@144.00000",
  position = "auto-center-right",
  scale = "1",
})


